[package]
name = "buildxargs"
version = "1.2.0"
edition = "2021"
authors = ["Pierre Fenoll <pierrefenoll@gmail.com>"]
description = "xargs for BuildKit with docker buildx bake"
keywords = ["xargs", "buildkit", "docker", "visualization"]
license = "MIT"
repository = "https://github.com/fenollp/buildxargs"

[dependencies]
assert_no_alloc = "1"
clap = { version = "4", features = ["derive", "color"] }
no-panic = "0.1"
shlex = "1"
tempfile = "3"

[dev-dependencies]
assert_cmd = "2"
assert_fs = "1"
predicates = "3"

[profile.dev]
lto = "thin"  # no_panic
opt-level = 1 # no_panic

[profile.test]
lto = "thin"  # no_panic
opt-level = 1 # no_panic
