[package]
name = "buildxargs"
version = "1.1.0"
edition = "2021"
authors = ["Pierre Fenoll <pierrefenoll@gmail.com>"]
description = "xargs for BuildKit with docker buildx bake"
keywords = ["xargs", "buildkit", "docker", "visualization"]
license = "MIT"
repository = "https://github.com/fenollp/buildxargs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive", "color"] }
tempfile = "3"
shlex = "1"
