on: [push]
name: buildx
jobs:


  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ludeeus/action-shellcheck@2.0.0
      with:
        check_together: 'yes'


  well:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: actions/checkout@v3

    # - uses: actions-rs/cargo@v1
    #   with:
    #     command: fetch
    - run: |
      mkdir -p $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/
      curl -#fsSLo "$CARGO_HOME"/registry/src/github.com-1ecc6299db9ec823/v1.0.3.zip https://github.com/sunfishcode/io-lifetimes/archive/refs/tags/v1.0.3.zip
      cd $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/io-lifetimes-1.0.3/ && unzip v1.0.3.zip && cd -

    - uses: docker/setup-buildx-action@v2

    - run: RUSTCBUILDX_DEBUG=1 ./well.sh


  tryin-sequential:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: actions/checkout@v3

    - uses: actions-rs/cargo@v1
      with:
        command: fetch

    - uses: docker/setup-buildx-action@v2

    - run: |
      ls -lha /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/io-lifetimes-1.0.3 || true
      ls -lha /home/runner/.cargo/registry/src/*/io-lifetimes-1.0.3 || true
      ls -lha /home/runner/.cargo/registry/src/*/io-lifetimes-* || true
    - run: if RUSTCBUILDX_DEBUG=1 CARGO_TARGET_DIR=$PWD/_target ./tryin.sh; then echo YAY; else echo FAILED && tree _target && exit 1; fi


  wrapped-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: actions/checkout@v3

    - uses: actions-rs/cargo@v1
      with:
        command: fetch

    - uses: docker/setup-buildx-action@v2

    - run: RUSTCBUILDX_DEBUG=1 RUSTC_WRAPPER=$PWD/tryin.sh cargo -vv build --locked --frozen --offline --all-targets --all-features


  wrapped-build-with-target:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: actions/checkout@v3

    - uses: actions-rs/cargo@v1
      with:
        command: fetch

    - uses: docker/setup-buildx-action@v2

    - run: CARGO_TARGET_DIR=$PWD/target RUSTCBUILDX_DEBUG=1 RUSTC_WRAPPER=$PWD/tryin.sh cargo -vv build --locked --frozen --offline --all-targets --all-features
