on: [push]
name: buildx
jobs:


  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ludeeus/action-shellcheck@2
      with:
        check_together: 'yes'


  well:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: actions/checkout@v3

    - uses: actions-rs/cargo@v1
      with:
        command: fetch

    - uses: docker/setup-buildx-action@v2

    - run: RUSTCBUILDX_DEBUG=1 ./well.sh


  tryin-sequential:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: actions/checkout@v3

    - uses: actions-rs/cargo@v1
      with:
        command: fetch

    - uses: docker/setup-buildx-action@v2

    - run: if RUSTCBUILDX_DEBUG=1 CARGO_TARGET_DIR=$PWD/_target ./tryin.sh; then echo YAY; else echo FAILED && tree _target && exit 1; fi


  wrapped-release-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: actions/checkout@v3

    - uses: actions-rs/cargo@v1
      with:
        command: fetch

    - uses: docker/setup-buildx-action@v2

    - run: RUSTCBUILDX_DEBUG=1 RUSTC_WRAPPER=$HOME/wefwefwef/buildxargs.git/tryin.sh cargo build --locked --frozen --offline --all-targets --all-features
