on: [push]

name: CI

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features
    - uses: actions-rs/cargo@v1
      with:
        command: run
        args: |
          -- <<EOF
          docker build --build-arg ARGs='--format mp4 -- https://www.youtube.com/watch?v=Hj7LwZqTflc' --output=/home/pete/ https://github.com/fenollp/dockerhost-tools--yt-dlp.git#main
          docker build --build-arg ARGs='--format mp4 -- https://www.youtube.com/watch?v=dMT9PVmwW70' --output=/home/pete/ https://github.com/fenollp/dockerhost-tools--yt-dlp.git#main
          docker build --build-arg ARGs='--format mp4 -- https://www.youtube.com/watch?v=kZ8E_lDQm-g' --output=/home/pete/ https://github.com/fenollp/dockerhost-tools--yt-dlp.git#main
          docker build --build-arg ARGs='--format mp4 -- https://www.youtube.com/watch?v=NgZeYxl3aL8' --output=/home/pete/ https://github.com/fenollp/dockerhost-tools--yt-dlp.git#main
          docker build --build-arg ARGs='--format mp4 -- https://www.youtube.com/watch?v=3XK-xhpAbIM' --output=/home/pete/ https://github.com/fenollp/dockerhost-tools--yt-dlp.git#main
          docker build --build-arg ARGs='--format mp4 -- https://www.youtube.com/watch?v=iw3EdKNvm_g' --output=/home/pete/ https://github.com/fenollp/dockerhost-tools--yt-dlp.git#main
          EOF
    - run: |
        cat >commands.txt <<EOF
        docker build --build-arg ARGs='--format mp4 -- https://www.youtube.com/watch?v=Hj7LwZqTflc' --output=/home/pete/ https://github.com/fenollp/dockerhost-tools--yt-dlp.git#main
        docker build --build-arg ARGs='--format mp4 -- https://www.youtube.com/watch?v=dMT9PVmwW70' --output=/home/pete/ https://github.com/fenollp/dockerhost-tools--yt-dlp.git#main
        docker build --build-arg ARGs='--format mp4 -- https://www.youtube.com/watch?v=kZ8E_lDQm-g' --output=/home/pete/ https://github.com/fenollp/dockerhost-tools--yt-dlp.git#main
        docker build --build-arg ARGs='--format mp4 -- https://www.youtube.com/watch?v=NgZeYxl3aL8' --output=/home/pete/ https://github.com/fenollp/dockerhost-tools--yt-dlp.git#main
        docker build --build-arg ARGs='--format mp4 -- https://www.youtube.com/watch?v=3XK-xhpAbIM' --output=/home/pete/ https://github.com/fenollp/dockerhost-tools--yt-dlp.git#main
        docker build --build-arg ARGs='--format mp4 -- https://www.youtube.com/watch?v=iw3EdKNvm_g' --output=/home/pete/ https://github.com/fenollp/dockerhost-tools--yt-dlp.git#main
        EOF
    - uses: actions-rs/cargo@v1
      with:
        command: run
        args: -- -f commands.txt --debug --print
    - uses: actions-rs/cargo@v1
      with:
        command: run
        args: -- -f commands.txt

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - run: rustup component add rustfmt
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - run: rustup component add clippy
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --all-targets --all-features --  -D warnings -W clippy::all
